- name: set test variables
  ansible.builtin.set_fact:
    token: vaulttoken
    vaulturl: vaultaddress

- name: Return latest KV v2 secret from path
  hosts: localhost
  gather_facts: false
  tasks:
    - name: path ansible
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=/kv/data/deneme token={{ token }} url={{ vaulturl }}') }}"
      register: key_value
    - debug: var=key_value.msg.ad